spring.application.name=ordenes-service
server.port=${PORT:8081}

# Conexi\u00f3n a Neon PostgreSQL en la nube
spring.datasource.url=jdbc:postgresql://ep-polished-lake-aqo6d7n4.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BFzNZIf35Rxe
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect