spring.application.name=ordenes-service
server.port=8081

# Conexi\u00f3n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ordenes
spring.datasource.username=postgres
spring.datasource.password=root

# Configuraci\u00f3n de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true